<?php

 
/**
 * This is the model base class for the table "{{retailer_wholesaler}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RetailerWholesaler".
 *
 * Columns in table "{{retailer_wholesaler}}" available as properties of the model,
 * followed by relations of table "{{retailer_wholesaler}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $retailer_id
 * @property integer $wholesaler_id
 * @property integer $state_id
 * @property integer $type_id
 * @property string $create_time
 * @property string $update_time
 * @property integer $create_user_id
 *
 * @property User $createUser
 * @property Retailer $retailer
 * @property Wholesaler $wholesaler
 */
abstract class BaseRetailerWholesaler extends GxActiveRecord {

	
	public static function getStatusOptions($id = null)
	{
		$list = array("Draft","Published","Archive");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}	
	public static function getTypeOptions($id = null)
	{
		$list = array("TYPE1","TYPE2","TYPE3");
		if ($id == null )	return $list;
		if ( is_numeric( $id )) return $list [ $id ];
		return $id;
	}
 	public function beforeValidate()
	{
		if($this->isNewRecord)
		{
			if ( !isset( $this->create_time )) $this->create_time = date( 'Y-m-d H:i:s');
				if ( !isset( $this->create_user_id )) $this->create_user_id = Yii::app()->user->id;			
	}else{
					}
		return parent::beforeValidate();
	}

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{retailer_wholesaler}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'RetailerWholesaler|RetailerWholesalers', $n);
	}

	public static function representingColumn() {
		return 'create_time';
	}

	public function rules() {
		return array(
			array('retailer_id, wholesaler_id', 'required'),
			array('retailer_id, wholesaler_id, state_id, type_id, create_user_id', 'numerical', 'integerOnly'=>true),
			array('id, retailer_id, wholesaler_id, state_id, type_id, create_time, update_time, create_user_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'createUser' => array(self::BELONGS_TO, 'User', 'create_user_id'),
			'retailer' => array(self::BELONGS_TO, 'Retailer', 'retailer_id'),
			'wholesaler' => array(self::BELONGS_TO, 'Wholesaler', 'wholesaler_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'retailer_id' => null,
			'wholesaler_id' => null,
			'state_id' => Yii::t('app', 'State'),
			'type_id' => Yii::t('app', 'Type'),
			'create_time' => Yii::t('app', 'Create Time'),
			'update_time' => Yii::t('app', 'Update Time'),
			'create_user_id' => null,
			'createUser' => null,
			'retailer' => null,
			'wholesaler' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('retailer_id', $this->retailer_id);
		$criteria->compare('wholesaler_id', $this->wholesaler_id);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('type_id', $this->type_id);
		$criteria->compare('create_time', $this->create_time, true);
		$criteria->compare('update_time', $this->update_time, true);
		$criteria->compare('create_user_id', $this->create_user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}